#端口号配置
server:
  port: 12345
#数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: wu123456
  jackson:
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #配置mybatis plus 在更新时只更新非空和非NULL的字段
      update-strategy: not_empty
#日志配置
logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'

#图片上传
web:
  upload-path: E:/Mycode/MyGraduationProject/image/   #图片上传的路径
  load-path: file:E://Mycode//MyGraduationProject//image/ #图片访问、加载的路径
